### ISSUE TITLE
Target features or roadmap needed

### ISSUE THREAD

**Issue by maniczirconium** [nikhilmwarrier/fluidcss#1]
What are the things we need to be working on first? Do we need to figure things out from scratch, or should we look to other frameworks as starting point?

**Comment by nikhilmwarrier** [comment]
Hey,
I suppose we should really add a Dark Mode switcher that can be activated in as less lines of javascript as possible and can be called upon by adding a dark-mode-switcher id to an element.

**Comment by nosoycesaros** [comment]
Hey! it's a minor thing, but a getting started in the Readme is always a good improvement

**Comment by nikhilmwarrier** [comment]
@nosoycesaros Sure! I have created a roadmap and will post it as soon as possible. Check back the README occasionaly...

**Comment by nikhilmwarrier** [comment]
I have now added the roadmap to the `main` repo. Check it out [here](https://github.com/nikhilmwarrier/fluidcss/blob/main/README.md)
