### ISSUE TITLE
Wrong link in README file

### ISSUE THREAD

**Issue by kimlimjustin** [nikhilmwarrier/fluidcss#5]
You wrote the `gh-pages` link as https://github.com/nikhilmwarrier/fluidcss/blob/gh-pages/ and it result to 404 page not found. Do you mean https://github.com/nikhilmwarrier/fluidcss/tree/gh-pages ?

**Comment by nikhilmwarrier** [comment]
Thanks for pointing it out, @kimlimjustin, I hadn't noticed it earlier. I will surely fix it.
