### ISSUE TITLE
Found a bug on ducumentation page

### ISSUE THREAD

**Issue by kimlimjustin** [nikhilmwarrier/fluidcss#6]
Hello, when I visited the documentation page of this framework, I accidentally see this bug on the page
![Screenshot (65)_LI](https://user-images.githubusercontent.com/61906684/99259126-264ae480-284c-11eb-9dc5-740ea4e8e862.jpg)

**Comment by nikhilmwarrier** [comment]
I guess it has something to do with margins.....
I will try to find out the reason...
Thsnks for reporting, btw

**Comment by nikhilmwarrier** [comment]
*thanks

**Comment by kimlimjustin** [comment]
You're welcome

**Comment by nikhilmwarrier** [comment]
Hey! Can you tell me how to reproduce this bug? It doesn't appear at all on my screen, even in DevTools

**Comment by kimlimjustin** [comment]
I opened the documentation page on chrome browser and it appears without touching anything. 
Attachment: https://drive.google.com/file/d/1efHceMHUZwuFn-S-NziUEQT5vkKtWKlH/view?usp=sharing (screen record when I open the documentation page)

I think the reason is the padding of the highlight class. Maybe you can try to change the padding to 0.4 rem. I tried it and the bug is gone and become normal.

**Comment by kimlimjustin** [comment]
Chrome version: Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by nikhilmwarrier** [comment]
Ook! I actually tested on Firefox, but forgot to test on Chrome before pushing my commits due to time issues [read: laziness]. Anyway, thanks a lot for taking effort to bring it under my notice...
